explain create table t1 (col1 int, col2 str);
-- explain create table t2 as (select * from t1); not supported
explain drop table t1;
explain cast col1 from t1 to int;
explain import t1 from 'path.csv';
explain export t1 to 'path.csv';
explain insert into t1 values (1, 'a');
explain select * from t1;
explain select * from t1 where col1 = 1;
explain select distinct col from t1;
explain select * from t1 where col1 = 1 order by col1;
explain select * from t1 where col1 > 1 order by col1 desc;
explain select * from t1 where col1 >= 1 order by col1 top 3;
explain lock table t1 mode X;
explain lock table t1 mode S;
explain unlock table t1;
explain unlock table t1 force;
explain delete from t1 where col1 = 1;
explain update table t1 set col2 = 'b' where col1 = 1;
explain create index idx on t1 (col1) using btree;
explain drop index idx;
